apiVersion: app/v1
kind: Deployment
metadata:
   name: deployment
   labels:
    tier: frontend

spec:
  template:
     metadata:
       name: webapp-pod
       labels:
          type: frontend
     spec:
       containers:
         - name: webapp
           image: nginx

  replicas: 3
  selector:
    matchLabels:
      type: frontend