apiVersion: v1
kind: ReplicationController
metadata:
   name: rc-controller
   labels:
    tier: frontend

spec:
  template:
     metadata:
       name: webapp-pod
       labels:
          type: frontend
     spec:
       containers:
         - name: webapp
           image: nginx

  replicas: 3